wtf:
  colors:
    background: "black"
    border:
      Focusable: "darkslateblue"
      focused: "orange"
      normal: "gray"
  grid:
    # How _wide_ the columns are, in terminal characters. In this case we have
    # six columns, each of which are 35 characters wide
    columns: [35, 35, 35, 35, 35, 35]

    # How _high_ the rows are, in terminal lines. In this case we have five rows
    # that support ten line of text, one of three lines, and one of four
    rows: [10, 10, 10, 10, 10, 3, 4]
  # The app redraws itself once a second
  openFileUtil: open
  refreshInterval: 1
  term: "xterm-256color"
